# fly.toml app configuration file generated for effectful-punster-api on 2025-03-09T14:39:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'effectful-punster-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
